terraform {
  
  backend "s3" {
    bucket = "statefile-terraform-15032026"
    key = "terraform.tfstate" #if same pth already using in diff directory not a good practice to use here
    #key = "day2/terraform.tfstate" #good practice to use here
    region = "us-east-1"
    
  }
}
# here we are using the same bucket but different key for different days so that we can have separate state files for each day and we can also have a common state file for all the days if we want to use the same state file for all the days then we can use the same key for all the days and then we can have a common state file for all the days and we can also have a common state file for all the days if we want to use the same state file for all the days then we can use the same key for all the days and then we can have a common state file for all the days and we can also have a common state file for all the days if we want to use the same state file for all the days then we can use the same key for all the days and then we can have a common state file for all the days and we can also have a common state file for all the days if we want to use the same state file for all the days then we can use the same key for all the days and then we can have a common state file for all the days and we can also have a common state file for all the days if we want to use the same state file for all the days then we can use the same key for all the days and then we can have a common state file for all the days and we can also have a common state file for all the days if we want to use the same state file for all the days then we can use the same key for all the days and then we can have a common state file for all the days and we can also have a common state file for all the days if we want to use the same state file for all the days then we can use the same key for all the days and then we can have a common state file for all the days and we can also have a common state file for all the days if we want to use the same state file for all the days then we can use the same key for all the days and then we can have a common state file for all the days and we can also have a common state file for all the days if we want to use the same state file for all the days then we can use the same key for all the days and then we can have a common state file for all the days and we can also have a common state file for all the days if we want to use the same state file for all the days
#if we use common s3 path for two diff directories you may destory or modify existing resources 